# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Validate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: brew install go-task/tap/go-task 
      - run: brew tap go-swagger/go-swagger && brew install go-swagger
      
      - name: Validate swagger
        run: task swagger.validate
      
